#!/usr/bin/env python3
"""OpenHands agent-server against Boxed on the same host type.

Usage: openhands.py <results_dir> <out_tables_dir> <OPENHANDS_RUN> <BOXED_RUNC_RUN>
Emits tables/openhands.tex (lifecycle + escape summary) and tables/numbers-openhands.tex.
"""
import glob, sys
from pathlib import Path
import numpy as np, pandas as pd

def pooled(run, name):
    fs = sorted(glob.glob(str(run / f"r*/{name}")))
    return pd.concat([pd.read_csv(f) for f in fs], ignore_index=True) if fs else None

def escapes(run):
    fs = sorted(glob.glob(str(run / "escapes_r*.csv")))
    E = [pd.read_csv(f).set_index("test") for f in fs]
    consistent = all(e["postcondition"].equals(E[0]["postcondition"]) for e in E)
    return E[0], len(E), consistent

res, tout, oh_run, bx_run = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]), Path(sys.argv[4])
oh = pooled(res / oh_run, "coldstart.csv"); bx = pooled(res / bx_run, "coldstart.csv")
ohE, ohRuns, ohCons = escapes(res / oh_run); bxE, bxRuns, bxCons = escapes(res / bx_run)
m = {}
m["OHMedian"] = f"{np.median(oh['total_ms'])/1000:.1f}\\,s"; m["OHCreate"] = f"{np.median(oh['create_ms'])/1000:.1f}\\,s"
m["OHExec"] = f"{np.median(oh['first_exec_ms']):.0f}\\,ms"; m["OHDestroy"] = f"{np.median(oh['destroy_ms']):.0f}\\,ms"
m["OHN"] = str(len(oh)); m["OHPNinetyFive"] = f"{np.percentile(oh['total_ms'],95)/1000:.1f}\\,s"
m["OHNonZeroExit"] = str(int((oh["exit_code"] != 0).sum()))
m["OHDenied"] = str(int((ohE["postcondition"] == "DENIED").sum())); m["OHRuns"] = str(ohRuns); m["OHConsistent"] = "identical" if ohCons else "NOT identical"
m["OHVsBoxed"] = f"{np.median(oh['total_ms'])/np.median(bx['total_ms']):.0f}$\\times$"
und = [t for t, r in ohE.iterrows() if r["postcondition"] != "DENIED"]
m["OHUndeniedList"] = ", ".join(f"\\texttt{{{t.replace('_', chr(92)+'_')}}}" for t in und)
DIG = {"0":"Zero","1":"One","2":"Two","3":"Three","4":"Four","5":"Five","6":"Six","7":"Seven","8":"Eight","9":"Nine"}
for t in ohE.index:
    key = "".join(DIG.get(c, c) for c in "".join(w.capitalize() for w in t.split("_")))
    m[f"OHEv{key}"] = str(ohE.loc[t, "evidence"]).replace("_", "\\_").replace("%", "\\%").replace("&", "\\&")[:90]
post = (res / oh_run / "posture.txt")
if post.exists():
    txt = post.read_text()
    m["OHPosture"] = txt.splitlines()[0].replace("_", "\\_")
    m["OHMetadataReachable"] = "yes" if "boxed-rt" in txt or "ya29." in txt or "access_token" in txt else "no"
    m["OHSudo"] = "passwordless sudo works" if "uid=0(root)" in txt else "no passwordless sudo"
L = ["\\begin{table}[t]", "\\centering",
     "\\caption{OpenHands agent-server and Boxed (runc, hardened) on the same host type, same harness. Lifecycle medians in ms over $n$ cycles; post-condition escape verdicts, identical across 3 runs.}",
     "\\label{tab:openhands}", "\\scriptsize", "\\setlength{\\tabcolsep}{2.5pt}", "\\begin{tabular}{@{}lrrrrrr@{}}", "\\toprule",
     "System & $n$ & create & first exec & destroy & total & denied \\\\", "\\midrule",
     f"OpenHands agent-server & {len(oh)} & {np.median(oh['create_ms']):.0f} & {np.median(oh['first_exec_ms']):.0f} & {np.median(oh['destroy_ms']):.0f} & \\textbf{{{np.median(oh['total_ms']):.0f}}} & {m['OHDenied']}/12 \\\\",
     f"Boxed, runc & {len(bx)} & {np.median(bx['create_ms']):.0f} & {np.median(bx['first_exec_ms']):.0f} & {np.median(bx['destroy_ms']):.0f} & \\textbf{{{np.median(bx['total_ms']):.0f}}} & {int((bxE['postcondition']=='DENIED').sum())}/12 \\\\",
     "\\bottomrule", "\\end{tabular}", "\\end{table}"]
(tout / "openhands.tex").write_text("\n".join(L) + "\n")
(tout / "numbers-openhands.tex").write_text("% AUTO-GENERATED by bench/analyze/openhands.py -- do not edit by hand.\n" + "\n".join(f"\\newcommand{{\\{k}}}{{{v}\\xspace}}" for k, v in m.items()) + "\n")
print(f"openhands: n={len(oh)} median {np.median(oh['total_ms']):.0f} ms, denied {m['OHDenied']}/12; undenied: {und}", file=sys.stderr)
