#!/usr/bin/env python3
"""Throughput against host core count.

Usage: scaling.py <results_dir> <out_tables_dir> <out_figures_dir> RUN:cores ...
  e.g. scaling.py results ../paper-v2/tables ../paper-v2/figures linux-2026-09:4 linux-8core-2026-09:8 linux-16core-2026-09:16
"""
from __future__ import annotations
import glob, sys
from pathlib import Path
import numpy as np, pandas as pd
from scipy import stats as sps
import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
plt.rcParams.update({"font.family": "serif", "font.size": 8, "axes.labelsize": 8, "legend.fontsize": 7,
                     "figure.dpi": 200, "savefig.bbox": "tight", "savefig.pad_inches": 0.02})

def main():
    res, tout, fout = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    specs = [a.split(":") for a in sys.argv[4:]]
    WORD = {"4": "Four", "8": "Eight", "16": "Sixteen", "32": "ThirtyTwo", "2": "Two"}
    fig, ax = plt.subplots(figsize=(3.4, 2.0))
    macros, T = {}, []
    for run, cores in specs:
        tps = sorted(glob.glob(str(res / run / "tp*/throughput.csv")))
        if not tps: continue
        tp = pd.concat([pd.read_csv(p) for p in tps]); g = tp.groupby("conc")["rps"]
        mean, sd, n = g.mean(), g.std(ddof=1), g.count()
        ci = sps.t.ppf(0.975, n - 1) * sd / np.sqrt(n)
        ax.errorbar(mean.index, mean, yerr=ci, marker="o", capsize=2, lw=1.1, label=f"{cores} vCPU ({len(tps)} sweeps)")
        best = mean.idxmax()
        macros[f"ScalePeak{WORD[cores]}"] = f"{mean[best]:.1f}"; macros[f"ScalePeakConc{WORD[cores]}"] = str(int(best)); macros[f"ScalePeakCI{WORD[cores]}"] = f"$\\pm${ci[best]:.1f}"
        macros[f"ScaleAtOne{WORD[cores]}"] = f"{mean[1]:.1f}"
        lo, hi = mean.min(), mean.max()
        T.append((cores, len(tps), mean[1], mean[best], int(best), ci[best], mean.get(32, float('nan'))))
    ax.set_xscale("log", base=2); ax.set_xlabel("client concurrency"); ax.set_ylabel("sandboxes / s")
    ax.legend(frameon=False, loc="lower right"); ax.grid(True, alpha=0.3); ax.set_ylim(bottom=0)
    fig.savefig(fout / "scaling.pdf"); plt.close(fig)
    if len(T) >= 2:
        macros["ScaleRatioMax"] = f"{T[-1][3]/T[0][3]:.1f}$\\times$"
        macros["ScaleCoreRatio"] = f"{int(T[-1][0])//int(T[0][0])}$\\times$"
    L = ["\\begin{table}[t]", "\\centering", "\\caption{Throughput against host core count (GCE \\texttt{n2-standard-\\{4,8,16\\}}, native runc, create$\\rightarrow$destroy lifecycles, 80 per level). Mean sandboxes/s with 95\\% CI at the best level.}",
         "\\label{tab:scaling}", "\\footnotesize", "\\begin{tabular}{@{}rrrrrr@{}}", "\\toprule",
         "vCPU & sweeps & at $c{=}1$ & peak & at $c$ & at $c{=}32$ \\\\", "\\midrule"]
    for cores, ns, one, pk, bc, ci, c32 in T:
        L.append(f"{cores} & {ns} & {one:.1f} & \\textbf{{{pk:.1f}}} $\\pm${ci:.1f} & {bc} & {c32:.1f} \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (tout / "scaling.tex").write_text("\n".join(L) + "\n")
    (tout / "numbers-scaling.tex").write_text("% AUTO-GENERATED by bench/analyze/scaling.py -- do not edit by hand.\n" + "\n".join(f"\\newcommand{{\\{k}}}{{{v}\\xspace}}" for k, v in macros.items()) + "\n")
    print(f"scaling: {[s for s in specs]} -> tables/scaling.tex, figures/scaling.pdf", file=sys.stderr)

if __name__ == "__main__":
    main()
