#!/usr/bin/env python3
"""Emit LaTeX \newcommand macros from bench CSVs.

Usage: stats.py <results_dir> <out_tables_dir>
Produces <out_tables_dir>/numbers.tex with macros consumed by paper/main.tex.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd


def fmt_ms(x: float) -> str:
    if x >= 1000:
        return f"{x/1000:.2f}\\,s"
    return f"{x:.0f}\\,ms"


def main():
    if len(sys.argv) != 3:
        print("usage: stats.py <results_dir> <out_tables_dir>", file=sys.stderr)
        sys.exit(2)
    results = Path(sys.argv[1])
    out = Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)

    macros: dict[str, str] = {
        # All macros referenced by paper/main.tex must have a default so the build
        # never breaks when a CSV is missing.
        "BoxedColdMedian": "TBD",
        "BoxedColdPNinetyFive": "TBD",
        "BoxedColdPNinetyNine": "TBD",
        "BoxedCreateMedian": "TBD",
        "BoxedColdN": "TBD",
        "BoxedPeakRPS": "TBD",
        "BoxedPeakConc": "TBD",
        "BoxedRSSMedian": "TBD",
        "BoxedRSSPNinetyFive": "TBD",
        "BoxedCPUMedian": "TBD",
        "BoxedEscapeDenied": "TBD",
        "BoxedEscapeTotal": "TBD",
        "BoxedEscapePct": "TBD",
        "BoxedAgentN": "TBD",
        "BoxedAgentPass": "TBD",
        "BoxedAgentLLMShare": "TBD",
        "BoxedAgentMedianTotal": "TBD",
        "BoxedAgentCreateMedian": "TBD",
    }

    cs = results / "coldstart.csv"
    if cs.exists():
        df = pd.read_csv(cs)
        total = df["total_ms"]
        macros["BoxedColdMedian"] = fmt_ms(np.median(total))
        macros["BoxedColdPNinetyFive"] = fmt_ms(np.percentile(total, 95))
        macros["BoxedColdPNinetyNine"] = fmt_ms(np.percentile(total, 99))
        macros["BoxedColdIQR"] = fmt_ms(np.percentile(total, 75) - np.percentile(total, 25))
        macros["BoxedCreateMedian"] = fmt_ms(np.median(df["create_ms"]))
        macros["BoxedColdN"] = str(len(df))

    th = results / "throughput.csv"
    if th.exists():
        df = pd.read_csv(th)
        macros["BoxedPeakRPS"] = f"{df['rps'].max():.1f}"
        macros["BoxedPeakConc"] = str(int(df.loc[df["rps"].idxmax(), "conc"]))

    ov = results / "overhead.csv"
    if ov.exists():
        df = pd.read_csv(ov)
        macros["BoxedRSSMedian"] = f"{np.median(df['rss_mib']):.1f}\\,MiB"
        macros["BoxedRSSPNinetyFive"] = f"{np.percentile(df['rss_mib'],95):.1f}\\,MiB"
        macros["BoxedCPUMedian"] = f"{np.median(df['cpu_pct']):.2f}\\%"

    es = results / "escapes.csv"
    if es.exists():
        df = pd.read_csv(es)
        denied = (df["result"] == "DENIED").sum()
        total = len(df)
        macros["BoxedEscapeDenied"] = str(denied)
        macros["BoxedEscapeTotal"] = str(total)
        macros["BoxedEscapePct"] = f"{100*denied/total:.0f}\\%" if total else "0\\%"

    ag = results / "agent_trace.csv"
    if ag.exists():
        df = pd.read_csv(ag, dtype={"passed": str})
        valid = df[df["passed"].isin(["true", "True", "false", "False"])].copy()
        if len(valid):
            passed_mask = valid["passed"].str.lower() == "true"
            llm = valid["llm_ms"].astype(float)
            create = valid["create_ms"].astype(float)
            exe = valid["exec_ms"].astype(float)
            destroy = valid["destroy_ms"].astype(float)
            total = llm + create + exe + destroy
            macros["BoxedAgentN"] = str(len(valid))
            macros["BoxedAgentPass"] = f"{100*passed_mask.sum()/len(valid):.0f}\\%"
            macros["BoxedAgentLLMShare"] = f"{100*llm.sum()/total.sum():.0f}\\%"
            macros["BoxedAgentMedianTotal"] = fmt_ms(np.median(total))
            macros["BoxedAgentCreateMedian"] = fmt_ms(np.median(create))

    lines = [
        "% AUTO-GENERATED by bench/analyze/stats.py — do not edit by hand.",
    ]
    for k, v in macros.items():
        lines.append(f"\\newcommand{{\\{k}}}{{{v}\\xspace}}")
    (out / "numbers.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote {out/'numbers.tex'} ({len(macros)} macros)", file=sys.stderr)


if __name__ == "__main__":
    main()
